### PR TITLE
Removes most above-tile lattices in the Enclave bunker.

### PR DESCRIPTION
**Pull request by LynxSolstice**
## About The Pull Request

Removes most above-tile lattices.

## Why It's Good For The Game

I'm of the personal opinion that the above-tile lattices make no sense to have randomly scattered about and are generally pretty ugly. So I removed most of them from the hallways and non-industrial rooms, or where they were not near a general position of disrepair.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:LynxSolstice
tweak: Removed most above-tile lattices in the Enclave bunker.
/:cl:

### CODE REVIEW

**Comment by Jawnner** [comment]
Lattice should stay, showcases the bunker being in a state of disrepair.

Intentional design choice.

**Comment by LynxSolstice** [comment]
> Lattice should stay, showcases the bunker being in a state of disrepair.
> 
> Intentional design choice.

I left it near the places in disrepair, to highlight such, rather than just randomly strewn about on top of tiles for no reason.

**Comment by spockye** [comment]
Put plating under the lattices, instead of tiles

**Comment by Stutternov** [comment]
Closing this as feedback given was mostly negative alongside narrative design of bunker looking run down being intentional.

**Pull request closed without merging**
