### PR TITLE
Removes Dogborg and furry mob sprites

### PR DESCRIPTION
**Pull request by Yobrocharlie**
real

## About The Pull Request

I like griefing (This PR actually just removes the furry super mutant/ghoul sprites and replaces them with their normal counterparts)

## Why It's Good For The Game

its not

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
del: Removed old things
/:cl:

### CODE REVIEW

**Comment by maaacha** [comment]
the dogborg sprites serve no use but they are still referenced in code. if you want to flat out remove the files you're going to need to go through and remove all references to them as well

**Comment by Yobrocharlie** [comment]
> the dogborg sprites serve no use but they are still referenced in code. if you want to flat out remove the files you're going to need to go through and remove all references to them as well

Fuck

**Comment by maaacha** [comment]
This now changes no files. If you want, I can go ahead and make the changes myself. I'd been meaning to, just hadn't gotten around to it.

**Comment by Yobrocharlie** [comment]
> This now changes no files. If you want, I can go ahead and make the changes myself. I'd been meaning to, just hadn't gotten around to it.

i can do it if you want ive just been busy.

**Comment by maaacha** [comment]
Superceded by #214

**Pull request closed without merging**
