### PR TITLE
removes integrated circuits and exosuit fabricators from R&D

### PR DESCRIPTION
**Pull request by zulixe**
## About The Pull Request

removes the research designs so they can no longer be printed, the items still remain in the game

## Why It's Good For The Game

- integrated circuits ~~are ripe for abuse~~ already disabled in config
- followers should not be able to produce mechs in their basement

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by zulixe** [comment]
btw if there are any other integrated circuit-related items in the protolathe, let me know so i can disable them too. i probably missed some of them

**Comment by zulixe** [comment]
all the more reason to remove them from R&D too, there's no sense in letting people print things they can't use

**Comment by Stutternov** [comment]
So zucking zased

**Comment by K4rlox** [comment]
mechs are already disabled, followers can only make a odyessus wich is a MEDICAL mech

**Comment by BadAtThisGame302** [comment]
Fallout 13 will not re-add and remove circuits for the millionth time:
Fallout 13:

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
