### PR TITLE
Shield Change (As Requested)

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Was requested to do this upon issues with shields. 

So, before some shields literally had the health of Bubblegum + armor on them as well. The health has been greatly reduced on some, some others have been buffed at lower end.

Telescopic shield has also been removed since it's busted as hell, had 2250 health, tons of armor, and such.

## Why It's Good For The Game

Some shields that were even labeled as removed were still in the game, like the Telescopic. Others got buffed by someone last week for some reason despite stam damage being fucked, etc.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
balance: Rebalances shields integrity.
removes: Telescopic shield (Use the riot, it's identical but just not telescopic.)
/:cl:

### CODE REVIEW

**Comment by Laus4Deus** [comment]
I like the reduction in each shield's health pool, notoriously because you can repair them with sheets of metal for most, so it's more about learning to when to retreat and repair.

My problem is that you are making the shields useless because of the `block_stamina_efficiency.` Particulary in the tower shield and scrap tower shield, you are bringing them down to a tenth of its original value!! Which is two and a half times worse than the placeholder shield!! If we go by that you should work from the placeholder as a parent and tweak each child after.

I understand that the problem with the BOS raid (this pr was made minutes after that round ended, let's not ignore cause and effect here) is that they were baffled by the tower shield shrugging off heavy fire, but that's no justification to make it useless. Why do I think it's useless?

With a damage absorption of 20 and a stamina efficiency of 1 you will end up in stamina crit after only a few shots. In that sense it's better to use the riot shield that would offer less protection and you rely on your armor but they don't put you to sleep (as fast)

I agree that `block_stamina_efficiency` was **very high at 10** but why not leave it at the minimum of 2.5? The two shields that were nerfed the most have **twice** the slowdown when blocking compared to the others. 

I want to put more thought into this besides making them bad. Maybe the buckler and the stop sign allows the user to run while blocking `var/block_lock_sprinting = FALSE` which favours a different playstyle. Then we have the legion, scrap and riot shields which would be standard and finally the tower/scrap tower shields which are slow but strong.

**Comment by Laus4Deus** [comment]
PS: The `var/block_damage_limit = 80` is another great variable to consider. It should be adjusted to the highest hitting bullets in game, which would be an indirect armour penetration factor, where the bullet just slams right through the shield and wounds the soldier. AMR and etc...

**Comment by Stutternov** [comment]
> I like the reduction in each shield's health pool, notoriously because you can repair them with sheets of metal for most, so it's more about learning to when to retreat and repair.
> 
> My problem is that you are making the shields useless because of the `block_stamina_efficiency.` Particulary in the tower shield and scrap tower shield, you are bringing them down to a tenth of its original value!! Which is two and a half times worse than the placeholder shield!! If we go by that you should work from the placeholder as a parent and tweak each child after.
> 
> I understand that the problem with the BOS raid (this pr was made minutes after that round ended, let's not ignore cause and effect here) is that they were baffled by the tower shield shrugging off heavy fire, but that's no justification to make it useless. Why do I think it's useless?
> 
> With a damage absorption of 20 and a stamina efficiency of 1 you will end up in stamina crit after only a few shots. In that sense it's better to use the riot shield that would offer less protection and you rely on your armor but they don't put you to sleep (as fast)
> 
> I agree that `block_stamina_efficiency` was **very high at 10** but why not leave it at the minimum of 2.5? The two shields that were nerfed the most have **twice** the slowdown when blocking compared to the others.
> 
> I want to put more thought into this besides making them bad. Maybe the buckler and the stop sign allows the user to run while blocking `var/block_lock_sprinting = FALSE` which favours a different playstyle. Then we have the legion, scrap and riot shields which would be standard and finally the tower/scrap tower shields which are slow but strong.

This was their value prior to Lolman's buff, that made their efficency 10. Thus draining no stamina damage via use.

While all other shields were not buffed at all and were still at 2.5, meaning tower shields were objectively the best thing ever. 

I was going to issue shields, such as the tower and riot shield variants, a number of 3 or 4 - but Maacha requested it be reduced. I know this won't be even too big of an issue due to chems restoring stamina rapidly anyway.

**Comment by Laus4Deus** [comment]
The current (well, previous) state of shields was product of a buff? It makes sense to restore them back then. I still want to see some extra tweaks done to them, but it's a matter of adaptation...

**Review by maaacha — APPROVED** [review]

**Pull request merged**
