### PR TITLE
Crafting Menu Reorganisation

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
## About The Pull Request

Reorganises the crafting tabs, removing some of them and merging them with others.

Explosive merged with ammo.
Belts, shoes, and clothing condensed into Wardrobe.
Tribal merged with primal.
Burial and electronics merged into miscellaneous

Fixes duplicate, non-functional tabs for pies and miscellaneous.

## Why It's Good For The Game

Tab list is no longer bloated. Hurray.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: Reorganised the crafting menu tabs.
fix: Removed duplicate, non-functional crafting menu tabs for miscellaneous and pies.
/:cl:

### CODE REVIEW

**Comment by Lamasmaster** [comment]
Why remove bottling, unless you intend to put it under the printer itself as recipes don't really see as to why.

**Comment by EvenInDeathIStillServe** [comment]
> Why remove bottling, unless you intend to put it under the printer itself as recipes don't really see as to why.

These are ports from coyote bayou. I thought they were removed for a reason. I'll add it back.

**Comment by Lamasmaster** [comment]
Don't know why CB removed them tbh, they were always just kinda there since DR2

**Comment by Draganfrukts** [comment]
> Burial, farming and electronics merged into miscellaneous
I would rather farming stays as its own category, since players will be drawn to it

**Comment by EvenInDeathIStillServe** [comment]
Done and done.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
