### PR TITLE
Great Oak Mountain Retreat, the final BoS rebase to end them all.

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

The complaints about "multi z" level combat and the tightness of the old Bunker are heard. This PR adds Old Oak Mountain Retreat Facility, used by the U.S Govt to establish control in the region in the event of nuclear war. This facility has been built out of a mountain with a bullet train that provides instantaneous transportation throughout the sewer system.

This PR will be in parts, the lower level has a reactor, areas needs to be set and other stuff too.

image

image

image
(The above might be touched up at a later date, being rushed here!)

## Why It's Good For The Game

In between the aforementioned "multi z level" issue, and how the old Bunker seriously needed a facelift, I thought I'll make this as an interim for the new map. The innate lootspawns in this bunker have been dumbed down but added utility has been added in place (plant disk/manip, holsters, ec)

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
Add: The final surface bunker to end all surface bunkers.
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
I'll comment when its ready, we should be up for a Saturday morning tm though!

**Comment by AllCorruptingWyrm** [comment]
image

image

image

Armory losses their supersledge -- they get an AER-9, 5 AEP7s, and a 10mm smg (GOOD)
They get additional pipboys too.
BoS are given broken HVACs to salvage like the Enclave's parking lot, and NCR's junkyard in Warren. (No need to feel compelled to salvage EVERY, SINGLE, CAR.)
ONE plant disk, and a built seed splicer. Less tedium. Need you get Gaia though.
10 MREs in the fridge, woo!
Shoulder holsters too.

One .50 mg, might need to be removed, we'll see.
That should be all the "questionable" stuff here. Let me know if I missed **anything.**

I advise we test merge it for a round and have someone on standby with TGs access to revert it, in case I missed something major, but every role spawns in and the reactor works fine too. We shouldn't have any issues.

There's a few easter eggs/flavortext items here, have fun finding the two. No, they don't impact anything, just descriptions & renames.

**Comment by AllCorruptingWyrm** [comment]
image
image
image
image
image

Changes ^

**Comment by lolman360** [comment]
image

these wooden fences are facing south when they should be facing north

(why are these ones wooden fences and the rest railings? no idea)

**Comment by AllCorruptingWyrm** [comment]
> image
> 
> these wooden fences are facing south when they should be facing north
> 
> (why are these ones wooden fences and the rest railings? no idea)

good find, I think I just got lazy, i'll do it tomorrow

**Comment by AllCorruptingWyrm** [comment]
image
Bunks on the Rooftop.

image
Moved the ORM and stuff around. Yay! Removed a locker.

image
Yes, I moved up their nest. Attackers can snipe them or use rockets. No they are not getting R walls or anything. The nest brings it in line with the Enclave base but in a different location

Also gave them Initiate armor (they were supposed to) and 2 more SMGs. Payment safe too, removed the innate cap spawns too. 

The Bunker should be equal points defendable as it is not defendable. Knights need to put legwork in.

**Review by maaacha — APPROVED** [review]

**Pull request merged**
