### PR TITLE
more dungeons

### PR DESCRIPTION
**Pull request by Yobrocharlie**
More dungeons

## About The Pull Request

This adds a few dungeons i spent time on at big iron, im porting them over here because I like em.

## Why It's Good For The Game

More content

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

New dungeons:
Chew chew
plant
oasis bunker
Enclave bunker
Gay baby jail

:cl:
add: Added new things
/:cl:

### CODE REVIEW

**Comment by maaacha** [comment]
i am going to have to spend some time reviewing this dungeons and making sure they are in line with our current loot level, as well as making sure all the mobs are spawning correctly

**Comment by Yobrocharlie** [comment]
> i am going to have to spend some time reviewing this and making sure they it is in line with our current loot level, as well as making sure all the mobs are spawning correctly

if you want me to change anything please let me know, i wish to have these places for fun not for the gamer gear.

**Comment by Yobrocharlie** [comment]
Would you like me to provide SS's?

**Comment by panzerr1944** [comment]
> Would you like me to provide SS's?

give screenshots, rough loot / mob lists, etc.

**Comment by AllCorruptingWyrm** [comment]
If you can shadow play as a ghost too, that'd be AWESOME.

**Comment by Yobrocharlie** [comment]
> If you can shadow play as a ghost too, that'd be AWESOME.

What you mean a ghost role spawn? That’s uh, probably won’t be a thing.

**Comment by Yobrocharlie** [comment]
> > Would you like me to provide SS's?
> 
> give screenshots, rough loot / mob lists, etc.

Give me a few hours

**Comment by Yobrocharlie** [comment]
Screenshot 2023-11-22 154740
Notable loot:
Functioning T-60, PA wear, gauss rifle, T5 armor spawn T5 melee spawn,
Notable enemies: Several normal deathclaws one mother one legenedary and one PA deathclaw

**Comment by Yobrocharlie** [comment]
Screenshot 2023-11-22 154759
Notable loot: T4 melee T5 ballistic spawn
Notable enemies: Venus fly traps, ludicrously annoyingly dangerous enemies who forcefully down you, knock your weapon out of youre hand, ignore armor, and can stun lock you if two get on you at once.

**Comment by Yobrocharlie** [comment]
Screenshot 2023-11-22 154828
The good old classic PA ruin,
Notable loot: Tribal PA and cleaving saw
Notable enemies: Power armor genetically modified deathclaw

**Comment by Yobrocharlie** [comment]
Screenshot 2023-11-22 154917

Notable loot: T-51 hardened and PA wear, along with a very high energy weapon spawn, two very high ballistic blueprint spawns and other misc gear
Notable enemies: Two very strong turrets, a very large amount of super mutants, and **Big chew chew** (also securi-chew) This may be a vast amount of loot but big chew chew is easily capable of solo-ing several factions and cannot be cheesed because they always try to get withen melee range and their bullets go through walls.

**Comment by Yobrocharlie** [comment]
Screenshot 2023-11-22 154934
Notable loot: Money and APA
Notable enemies: Several assaultrons, a few enclave soldier NPC's (very deadly and have no faction alignment) a few riot bots and a few assaultrons, along with more significantly PCU-11 a modified assaultron who has double the health double the speed and double the melee damage and who also has very degenerate examination text. And in order to actually unlock the rooms that have the APA you need to kill **captain arlem**

**Comment by panzerr1944** [comment]
> Screenshot 2023-11-22 154917
> 
> Notable loot: T-51 hardened and PA wear, along with a very high energy weapon spawn, two very high ballistic blueprint spawns and other misc gear Notable enemies: Two very strong turrets, a very large amount of super mutants, and **Big chew chew** (also securi-chew) This may be a vast amount of loot but big chew chew is easily capable of solo-ing several factions and cannot be cheesed because they always try to get withen melee range and their bullets go through walls.

you added my old big chew bunker. and didnt port in a big chew that works for this codebase?

**Comment by Yobrocharlie** [comment]
> > Screenshot 2023-11-22 154917
> > Notable loot: T-51 hardened and PA wear, along with a very high energy weapon spawn, two very high ballistic blueprint spawns and other misc gear Notable enemies: Two very strong turrets, a very large amount of super mutants, and **Big chew chew** (also securi-chew) This may be a vast amount of loot but big chew chew is easily capable of solo-ing several factions and cannot be cheesed because they always try to get withen melee range and their bullets go through walls.
> 
> you added my old big chew bunker. and didnt port in a big chew that works for this codebase?

that big chew chew works

**Comment by Yobrocharlie** [comment]
it appears that the CI integration check is just self failing

**Comment by panzerr1944** [comment]
> > > Screenshot 2023-11-22 154917
> > > Notable loot: T-51 hardened and PA wear, along with a very high energy weapon spawn, two very high ballistic blueprint spawns and other misc gear Notable enemies: Two very strong turrets, a very large amount of super mutants, and **Big chew chew** (also securi-chew) This may be a vast amount of loot but big chew chew is easily capable of solo-ing several factions and cannot be cheesed because they always try to get withen melee range and their bullets go through walls.
> > 
> > 
> > you added my old big chew bunker. and didnt port in a big chew that works for this codebase?
> 
> that big chew chew works

a var-edited one? idk. i'd leave out the chew bunker for now- I was gonna manually re-add an edited version somewhere myself.

**Comment by Yobrocharlie** [comment]
> > > > Screenshot 2023-11-22 154917
> > > > Notable loot: T-51 hardened and PA wear, along with a very high energy weapon spawn, two very high ballistic blueprint spawns and other misc gear Notable enemies: Two very strong turrets, a very large amount of super mutants, and **Big chew chew** (also securi-chew) This may be a vast amount of loot but big chew chew is easily capable of solo-ing several factions and cannot be cheesed because they always try to get withen melee range and their bullets go through walls.
> > > 
> > > 
> > > you added my old big chew bunker. and didnt port in a big chew that works for this codebase?
> > 
> > 
> > that big chew chew works
> 
> a var-edited one? idk. i'd leave out the chew bunker for now- I was gonna manually re-add an edited version somewhere myself.

if you say so panzer, ill delete it.

**Comment by Yobrocharlie** [comment]
it has been removed

**Comment by Yobrocharlie** [comment]
anything blocking this from being merged?

**Comment by maaacha** [comment]
> anything blocking this from being merged?

requires testing, has a lot of testing to do with balance that needs to be done before im going to merge it

**Comment by Yobrocharlie** [comment]
> > anything blocking this from being merged?
> 
> requires testing, has a lot of testing to do with mob and loot balance that needs to be done before im going to merge it

like?

**Comment by Yobrocharlie** [comment]
As far as im concerned loot wise there is nothing too revolutionary that the freaking enclave doesnt get round start or that the shopkeep can get.

**Comment by Hemlock32** [comment]
Lots of PA...
Three new sets of PA added to the map... Two of which are high-tier
Not sure I like

**Comment by Yobrocharlie** [comment]
> Lots of PA...
> Three new sets of PA added to the map... Two of which are high-tier
> Not sure I like

One is tribal, The other you got to do an extremely hard dungeon with several death laws and even a PA deathclaw which is death on this codebase.

And for the other you got to kill **_Arlem_** trust me bro it’s balanced, not to mention that these ruins actually let you use the PA unlike how the other ruins are where you get PA and have to scrap it to get what is a fairly now shit piece of armor.

I doubt either of the PA dungeons will ever be done and I **really** doubt either of them will be more meta than the current south bunker

**Comment by ApplePlastic** [comment]
> And in order to actually unlock the rooms that have the APA you need to kill captain arlem
doesn't arlem fullgib/instakill people or is this one varedited to Not Do That

**Comment by Stutternov** [comment]
Respect for attempt but find of conflicts & not updated for long period of time.

On new map I want to use sone of these tho. Overall very cool attempt.

**Pull request closed without merging**
