### PR TITLE
makes the khan heavy battlecoat sprite not asymmetrical

### PR DESCRIPTION
**Pull request by ApplePlastic**
what was this spriter cooking?

## About The Pull Request
Fixes the Khan Battlecoat's left sleeve. It was hilariously visible as to how asymmetrical it was. This PR fixes it. Simple as. 

## Why It's Good For The Game
erm.. sprite fix good? 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Legate-Maxson** [comment]
This sprite is going to be replaced anyway in a bit

**Comment by ApplePlastic** [comment]
> This sprite is going to be replaced anyway in a bit

replaced with what.....

**Comment by Legate-Maxson** [comment]
> > This sprite is going to be replaced anyway in a bit
> 
> replaced with what.....
khan

**Comment by ApplePlastic** [comment]
> > > This sprite is going to be replaced anyway in a bit
> > 
> > 
> > replaced with what.....
> > khan
> 
> The new sprites are slightly unfinished and just need touch ups. I'm finishing those now.

Zased!
closing this now, then, thanks 4 posting

**Pull request closed without merging**
