### PR TITLE
adds vox

### PR DESCRIPTION
**Pull request by lpeapnni**
## About The Pull Request
adds vox to the game
image

compatible with most clothing!
image
image

## Why It's Good For The Game
more species are always good, and i know of multiple people who would be appreciative of vox being added to fallout 13

as for people that think vox are too far-fetched for fallout, there are both furries and synthlizards in this server. this is a furry fallout server.

and in comparison to some shit like pokemon, i think vox are fairly grounded.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added vox
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
YOU'RE FOUR MONTHS OFF FOR THE APRIL FOOLS PR

**Comment by mazzinsanity** [comment]
No thanks

**Comment by Stutternov** [comment]
Yaya kikiki kinsies in Legions going helps Voxxy kill Presidents Kimballs kikiki

Trues to Ceasers!!!

**Comment by mazzinsanity** [comment]
> and in comparison to some shit like pokemon, i think vox are fairly grounded.

All pokemon-related markings have been either removed or renamed. Vox parts have also been removed.

**Comment by zeratino** [comment]
NO, NO, NOOOOOOOOOOO!!

CLOSE THIS, NOOOOOOOOOOOOW!!!!

**Comment by Lyroy** [comment]
More customization is good :] Maybe just rename them to something else? They could easily fit as ghoulified avians.

**Comment by lpeapnni** [comment]
> All pokemon-related markings have been either removed or renamed. Vox parts have also been removed.
i could rename them to "reptilians"

**Comment by Stutternov** [comment]
> No this is not being approved. Rebel, CLOSE THIS PR! NOW!!! @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov @Stutternov

o7

https://github.com/f13babylon/f13babylon/assets/47883419/5a94f223-c8c2-4268-9bf8-7a9ce455c8e6

**Pull request closed without merging**
