### PR TITLE
Update deathclaw.dm

### PR DESCRIPTION
**Pull request by SB1918**
Removes the most stupid mechanic I've ever seen in the existence of mechanics, that being mother deathclaw stungrab.

### CODE REVIEW

**Comment by panzerr1944** [comment]
disagree. There's no reason to nerf a mob that already does way less than it probably should.

**Comment by SB1918** [comment]
Instakill mechanics are not fun.

**Comment by panzerr1944** [comment]
Stunlock mechanics aren't fun. I agree with that- especially in PVP. However; this is a mob that you shouldn't really be fighting solo in the first place and is comically easy to cheese 99% of the time. It's weak enough as is, and is kind of a pushover compared to a more lore friendly claw.

It's going to kill you instantly anyways at the thresh-hold wherein it does the grab, as its melee swings do 30-50 dam usually and it only triggers at a value lower than 20HP. If it didn't aggro grab you and force drop you, you'd do that anyways by being hit. I'm genuinely not seeing the reason to get rid of it.

**Comment by Stutternov** [comment]
Feedback ultimately was negative, as by the time they do this you'd be dead already.

**Pull request closed without merging**
