### PR TITLE
removes gibtonite

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

I'm not gonna explain how this fucks up rounds & balance.

## Why It's Good For The Game

if you know, you know.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
tweak: removes gibtonite from spawning
/:cl:

### CODE REVIEW

**Comment by K4rlox** [comment]
honestly shit PR

its clwar you used replace all on every line including gibtonite, instead of just used "//" at the start of line to comment it you decided to change pathings of every single line

ontop of that, it runtimes
a lot
around 5 runtimes related to gibtonite when i ran it

**Comment by AllCorruptingWyrm** [comment]
heavens forbid I try, Zeratino asked me.

**Comment by CloverIsLucky** [comment]
Least salty PR.

**Comment by CloverIsLucky** [comment]
Just get a prospector pickaxe or.... just let them explode. I never saw anyone weaponizing them to see this a valid reason to remove them.

**Comment by maaacha** [comment]
sorry. this is a krill issue. PR closed.

**Pull request closed without merging**
