### PR TITLE
Rumors Welcomer

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
## About The Pull Request

Ports https://github.com/ARF-SS13/coyote-bayou/pull/4241 although with the variable tied to mob and not client.

Announces arrivals after 5 minutes, if they don't matrix.
States the name and role of the arrival to everyone in the same faction. Everyone else only sees the role of the arrival.
Departures work on the same system, except the announcement has no delay but only happens if their arrival was already announced (5 mins).
Enclave are referred to as Wastelander to non-Enclave.
Raiders and Wastelander factions do not see names.

## Why It's Good For The Game

Knowing who's in the playable area is always good for encouraging roleplay.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Arrivals and departures in the game area are now announced ICly.
/:cl:

### CODE REVIEW

**Comment by Malerus** [comment]
bruh no

**Comment by BadAtThisGame302** [comment]
Why is this good for the game? This is literally bring down the Roleplay. How does knowing "John Raider has joined the Wasteland" or whatever the fuck be GOOD for the game? Why is that good? It's not, it's going to be abused by factions to count how many hostiles are on, plus "Oh wait, I heard you joined as a Raider!! You're no Citizen man stop the cap!!" How is this "promoting" roleplay?

**Comment by EvenInDeathIStillServe** [comment]
> Why is this good for the game? This is literally bring down the Roleplay. How does knowing "John Raider has joined the Wasteland" or whatever the fuck be GOOD for the game? Why is that good? It's not, it's going to be abused by factions to count how many hostiles are on, plus "Oh wait, I heard you joined as a Raider!! You're no Citizen man stop the cap!!" How is this "promoting" roleplay?

Before I even begin answering, have you read the description of the PR?

**Comment by BadAtThisGame302** [comment]
> > Why is this good for the game? This is literally bring down the Roleplay. How does knowing "John Raider has joined the Wasteland" or whatever the fuck be GOOD for the game? Why is that good? It's not, it's going to be abused by factions to count how many hostiles are on, plus "Oh wait, I heard you joined as a Raider!! You're no Citizen man stop the cap!!" How is this "promoting" roleplay?
> 
> Before I even begin answering, have you read the description of the PR?

States the name and role of the arrival to everyone in the same faction. Everyone else only sees the role of the arrival.

This still will show the Jobs, perhaps no name which makes it slightly better. Unless you're in the same faction. Still, the same point goes for the factions which will just see the job.

**Comment by Malerus** [comment]
> .

bruh you forget, Enclave gets hidden behind Wastelander. like bruh

**Comment by EvenInDeathIStillServe** [comment]
> This still will show the Jobs, perhaps no name which makes it slightly better. Unless you're in the same faction. Still, the same point goes for the factions which will just see the job.

If you're against this, and yet are okay with being able to see the crew manifest in the lobby or while ghosting, then I don't know what to tell you.

**Comment by Malerus** [comment]
> > This still will show the Jobs, perhaps no name which makes it slightly better. Unless you're in the same faction. Still, the same point goes for the factions which will just see the job.
> 
> If you're against this, and yet are okay with being able to see the crew manifest in the lobby or while ghosting, then I don't know what to tell you.

crew manifest and ghosting are completely different things than getting complete in-character knowledge about an enemy faction bruh wtf r u doin bruh

**Comment by BadAtThisGame302** [comment]
> > This still will show the Jobs, perhaps no name which makes it slightly better. Unless you're in the same faction. Still, the same point goes for the factions which will just see the job.
> 
> If you're against this, and yet are okay with being able to see the crew manifest in the lobby or while ghosting, then I don't know what to tell you.

Being in the lobby and seeing the jobs then joining and then having NO NEW KNOWLEDGE OF ANYMORE PEOPLE WHO COME INTO THE JOBS YOU SAW. And if you are ghosted you already can observe anyone and everyone so removing the crew manifest from them, even if it may seem "meta" has no real difference from just observing everyone.

**Comment by SM45H** [comment]
If it only announced to the faction they were in, sure, maybe... It would serve as a good roll call on the coming and goings of the faction, but server wide? I only see this being used to meta people. I don't think this is a good idea if I'm honest. The benefit doesn't outweigh the cons for a server wide announcement system IMO.

**Comment by panzerr1944** [comment]
Getting to know that there's other people in your faction have come in or gone out? Cool and good.

Outside of that? I don't like it at all. It's just an IC version of the manifest that's really easy to abuse and removes any mystique.

**Comment by Fishpoker** [comment]
Tf is this bru just remove Explorer and ranger at this point

**Comment by EvenInDeathIStillServe** [comment]
> Tf is this bru just remove Explorer and ranger at this point

I'll do you one better. I'm removing the entire server.

**Pull request closed without merging**
