### PR TITLE
Re-Adds Priestess

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Suggestion made and was given this on a 'to-do' list. Tl;dr - Adds back priestess as not only a roleplay role but also a sort of MO equivalent role for Legion. Removes Priestess from orator but they get the same gear as they did before (baring armor and gun because sexism legion just be like that)

## Why It's Good For The Game

NCR has a bunch of medical slots, Legion could use a set dedicated medic instead of Aux having to take the specific medical loadout option. Plus this was specified not only in our lore document but asked for by players for roleplay role, and I know people really wanted more medical stuff for some reason.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Re-adds Priestess as a role, separates it off of the Orator loadout.
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
https://www.youtube.com/watch?v=-nnTI1d5XuM
We are so back.

**Comment by BadAtThisGame302** [comment]
Is this really Rebel or did someone steal his Git account?

**Comment by Stutternov** [comment]
> Is this really Rebel or did someone steal his Git account? 

They have my loved ones held hostage in the Syndicate lavaland base send help

**Comment by K4rlox** [comment]
doesnt have trait_tribal

givin hallucinations upon use of medicine

**Comment by Stutternov** [comment]
> doesnt have trait_tribal
> 
> 
> 
> givin hallucinations upon use of medicine
> 
> 
> 
> 
> 
> to mention for some reason axuillia too dont have the trait and get hallucinations

I'll fix that today, I knew something had to be off unless legion chemistry had suddenly changed (it hadn't).

**Comment by K4rlox** [comment]
> > doesnt have trait_tribal
> > givin hallucinations upon use of medicine
> > to mention for some reason axuillia too dont have the trait and get hallucinations
> 
> I'll fix that today, I knew something had to be off unless legion chemistry had suddenly changed (it hadn't).

i myself will make a PR tommorow to give tribal trait to roles in legion who dont have it

**Comment by Stutternov** [comment]
> > > doesnt have trait_tribal
> > > givin hallucinations upon use of medicine
> > > to mention for some reason axuillia too dont have the trait and get hallucinations
> > 
> > 
> > I'll fix that today, I knew something had to be off unless legion chemistry had suddenly changed (it hadn't).
> 
> i myself will make a PR tommorow to give tribal trait to roles in legion who dont have it

Fixed it now on this PR.

**Comment by K4rlox** [comment]
> > > > doesnt have trait_tribal
> > > > givin hallucinations upon use of medicine
> > > > to mention for some reason axuillia too dont have the trait and get hallucinations
> > > 
> > > 
> > > I'll fix that today, I knew something had to be off unless legion chemistry had suddenly changed (it hadn't).
> > 
> > 
> > i myself will make a PR tommorow to give tribal trait to roles in legion who dont have it
> 
> Fixed it now on this PR.

thanks

**Comment by maaacha** [comment]
Implemented in #84

**Pull request closed without merging**
