### PR TITLE
robot update/rework

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

does a lot of changes to robots
all changes TBD

robots are now much faster (0.3 slowdown instead of 1).
they are also somewhat tankier across the board to compensate for their lack of armor (0 armor btw)

robot modules have been revisited:
medical assaultron was rolled into medical borg and is now an altskin.
mining borg now has a shovel, and its emag module is a rocketsledge that mines better and has 12 less damage.
engiborg's emag module is also a rocketsledge (uncreative)
assaultron was rolled into secborg and is now an altskin.
vtec has been nerfed significantly from -1 slowdown to -0.25

gutsy flamethrower nerfed significantly: 1s firedelay, 33% lower projectile count, actual energy cost

all robots now have the wastebot faction, since all selectable sprites are fo13 robots anyways. this also makes slugs do 90 damage to them, which is extremely funny and something i might remove. again, tbd

## Why It's Good For The Game

as long as they're pickable they should be functional

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: new stuff to robots
del: old stuff from robots
tweak: robots can now patch nests
balance: robots are overall buffed (holy shit their slowdown was dogshit)
/:cl:

### CODE REVIEW

**Comment by K4rlox** [comment]
are you removing medical assaultron and adding back dogborgs

**Comment by lolman360** [comment]
> are you removing medical assaultron and adding back dogborgs

yes, medical assaultron got rolled into regular medical borg and is an altsprite for it now, as god intended

no, you cannot play dogborgs even after this update

**Comment by K4rlox** [comment]
> > are you removing medical assaultron and adding back dogborgs
> 
> yes, medical assaultron got rolled into regular medical borg and is an altsprite for it now, as god intended
> 
> no, you cannot play dogborgs even after this update

i see medassaultron removed and "medhound" being there

**Comment by lolman360** [comment]
> i see medassaultron removed and "medhound" being there

Please make sure you're taking a good look at the code and understanding exactly what things are being changed before you comment. Thanks!

**Comment by grade9fixer** [comment]
are you going to do anything to the gutsies w/ flamethrowers because uh

the no fire-delay flamethrower gutsies being even faster and tankier doesn't seem fun for anyone

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
