### PR TITLE
Substantially nerfs androids/cyborgs/gutsies.

### PR DESCRIPTION
**Pull request by grade9fixer**
## About The Pull Request

Reduces cyborg health from 300 -> 200.
Gutsies are also reduced to 200 HP.
Reduces cyborg movespeed.
Makes cyborgs stunned by EMPs for a little longer.

## Why It's Good For The Game

You can put your 'cope/ided' PR insults in my DMs.

But - on a serious note, cyborgs, especially combat cyborgs, are really broken at the moment, and I'm really surprised nobody's addressed them. The gutsy priorly had **450** health - mind you, cyborgs do not die when they hit 0 health. They have a crit status just like humans, meaning they die at -450 health, meaning that they currently have 900 health - the big difference between them and humans is that can keep fighting, even when in crit, and don't suffer from any damage slowdown. This, coupled with their insane speed, makes them the equivalent of a Paladin/APA unit/Heavy Trooper on fucking STEROIDS. 900 health, flamethrowers and plasma pistols + no slowdown. That's - not good, balanced or fun at all.

Additionally, the one counter against cyborgs isn't even that common outside of the BoS, and doesn't even stun them for that long. That's completely stupid.

This PR makes cyborgs somewhat combatable - 200 health is still really generous, given this gives them an effective health pool of 400. They're also less fast, which I feel is justified.

You can insult me all you want, you can call me a coper, you can shout at me for trying to cuck the Enclave, but - seriously. This isn't fun for anyone. 900 health gutsies. Just - let that sink in.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
balance: Cyborgs substantially nerfed - less health, slower, stunned for longer by EMPs.
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
Just giving my input - their 300 health is actually fine since they do not have the armor people think they do, taking raw damage.

Synthetic issues stem from 2 things:
- Their gun fire delays have been busted. It's because we keep pathing borg weapons separate. (I think I fixed this issue on my current up PR?)
- They can sprint infinitely. (Funnily, although they move fast default, they can't even climb over things or move over barbed wire.)

**Comment by grade9fixer** [comment]
> Just giving my input - their 300 health is actually fine since they do not have the armor people think they do, taking raw damage. Lowering the health makes them very, very weak vs a normal mob or human character.
> 
> Also - funny thing, synthetics - due to how they are coded - take super effective damage. So shooting them with an AMR will 1 tap them due to having like ~120-150 super effective damage and 40 damage atop of that.
> 
> Synthetic issues stem from 2 things:
> 
> * Their gun fire delays have been busted. It's because we keep pathing borg weapons separate. (I think I fixed this issue on my current up PR?)
> * They can sprint infinitely. (Funnily, although they move fast default, they can't even climb over things or move over barbed wire.)

The extra health is virtually armour, and whilst I relent they take supereffective damage - they can also just. Run away instantly and get it repaired. It's my opinion that cyborgs/gutsies shouldn't be strong / equal to humans - they can be mass-produced and there's almost no consequences for dying as one. I don't think we should really worry about them being 'vulnerable to humans' - that's sort of the point. They're meant to be more cannon fodder or specialised personnel than frontline fighters. As is, cyborgs/gutsies just move too fast, have insane survivability and can't really be killed unless they want to be killed, they're cornered, or you have a pulse rifle. It's just really not fun to play against, and I'm sure many people agree.

**Comment by HissyNays** [comment]
You are wrong.  Cyborgs are very, very weak, for one reason. They're not on super stims/bitters for the full duration of fight like everyone else. An average trooper/legionaire combined with their armor can eat up to 700 damage worth of bullets per fight and still survive. This is why cyborgs weren't ever that strong. Rather than nerfing their health, it'd be more reasonable to nerf their super speed.

**Comment by grade9fixer** [comment]
> You are wrong. Cyborgs are very, very weak, for one reason. They're not on super stims/bitters for the full duration of fight like everyone else. An average trooper/legionaire combined with their armor can eat up to 700 damage worth of bullets per fight and still survive. This is why cyborgs weren't ever that strong. Rather than nerfing their health, it'd be more reasonable to nerf their super speed.

> the welding tool in question

**Comment by ApplePlastic** [comment]
> You are wrong. Cyborgs are very, very weak, for one reason. They're not on super stims/bitters for the full duration of fight like everyone else. An average trooper/legionaire combined with their armor can eat up to 700 damage worth of bullets per fight and still survive. This is why cyborgs weren't ever that strong. Rather than nerfing their health, it'd be more reasonable to nerf their super speed.

the zero cooldown aep7 in question (the cyborg's using an autoclicker)

**Pull request closed without merging**
