### PR TITLE
Quality of Life improvement for multiple factions.

### PR DESCRIPTION
**Pull request by iMoeMoe**
## About The Pull Request

Added a couple of things to further improve qualities of the player's gameplay.

This include:

NCR:
-Re-organise the NCR Weaponry:

https://i.imgur.com/Uh1iwUo.png

-Add a bloodbank:

https://i.imgur.com/uL57vga.png

-Add 2 botany vendors to the farm:

https://i.imgur.com/W3LbJXD.png

Follower:

-Soothes out Chembay and gave a Deluxe Part box:

https://i.imgur.com/e6k3rWh.png

-Add autodoc, bloodbank and limbgrower to the follower's infirmary:

https://i.imgur.com/V0ZZaXt.png

-Add a Botany Dispenser and 2 botany vendors to the Follower's hydroponic, give them gaia and stimplants:

https://i.imgur.com/7ax64Kg.png

BoS:

-Give them gaia and stimplants:

https://i.imgur.com/9Y7FGb3.png

Enclave: 

-gave them stimplants and gaia:

https://i.imgur.com/oxqscnX.png

-dugged out another opening for them to mine:

https://i.imgur.com/cTLlSeY.png

Legion:

-Gave them a fullyupgraded drink dispenser and all the seeds needed for making bitter and poultice.

https://i.imgur.com/VsYplms.png

## Why It's Good For The Game

Cut down on the meta rush on gamestart loots and leave more for wastelander players to work with overall.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: MULTIPLE THINGS, CHECK THE PR.
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
List on this - Legion changes seem fine, 99% of NCR ones are fine. Going to bullet point the others.

- BOS slippery oil is funny but I can't approve that on a PR (I do not want cum in my mailbox)
- Enclave sissy hypno EIC board shouldn't be there, sissy hypno machine is to be removed from being built

As for the NCR limb regrower, I'm on the fence. On one hand, it's a minor thing. On the other, by having that more for the Followers it encourages their usage - and Legion doesn't get something like that and has to use cadavers. Going to ask a few balance devs about it and see.

**Review by Stutternov — CHANGES_REQUESTED** [review]
See above comment

**Comment by maaacha** [comment]
I've been told that a lot of the Followers changes are also already there, such as already having an Ore Silo and Autodoc board, and an ammolathe. The Followers Vendor is also completely redundant while they have access to RnD.

**Comment by iMoeMoe** [comment]
> List on this - Legion changes seem fine, 99% of NCR ones are fine. Going to bullet point the others.

> - BOS slippery oil is funny but I can't approve that on a PR (I do not want cum in my mailbox)
- Enclave sissy hypno EIC board shouldn't be there, sissy hypno machine is to be removed from being built
- Was on the fence about regrower, others asked that to be removed though. Reason why is it's a bit high tech for NCR and we want to encourage people to go to the Followers for that stuff. (Blood bank is fine tho) 

changes made and new additions added. (if Legion can have game start gaia then so should everyone else imo)

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
