### PR TITLE
POWERGAME-B-GONE | FALLOUT CHEMS NO LONGER STACK WITH BASE SS13 HEALING CHEMS

### PR DESCRIPTION
**Pull request by Draganfrukts**
### You've gotten a lot farther than you should have, but that is until you met someone that can make PRs. Your ride's over, powergamer. Time to get mogged.

**Most Fallout chems no longer stack with Med-X, Bicaridine, Salicylic Acid, Kelotane, Tricordrazine, Miner's Salve, Morphine or Oxandrolone.**

**Med-X may still stack with Imitation Stimfluid and Stimpaks, on top of the aforementioned chemicals.**

**Natural Painkillers don't stack with Berserker Powder. Berserker Powder doesn't stack with bitter drink.**

### CODE REVIEW

**Comment by panzerr1944** [comment]
disagree with medx not working with stims and whatnot. otherwise fine

**Comment by HissyNays** [comment]
What the fuck is this? Why are you straight up cutting out usefulness of chemistry and killing usefulness of medic role at the same time?

**Comment by gummardgumphrey** [comment]
> Why are you straight up cutting out usefulness of chemistry and killing usefulness of medic role at the same time? Why is this change completely avoiding legion exclusive chems? Wouldn't it make sense to then make berserker powder and natural painkillers not work with bitters? I know it's huge meme at this point but this is blatantly faction biased change. This needs to be cancelled.

image

thank goodness they changed this

**Comment by Laus4Deus** [comment]
There are too many ongoing changes in the server right now, I'd rather adjust to those first (as a player myself). Plus medicine in general has been tweaked a ton these last weeks

**Pull request closed without merging**
