### PR TITLE
event only enclave; the PR

### PR DESCRIPTION
**Pull request by panzerr1944**
## About The Pull Request
sets all enclave slots to 0
removes Casper
moves Enclave base to the No-Mans Land area

Someone was going to do this eventually - I'm biting the bullet and doing it myself as to avoid a full removal. With the new map still a work in progress and with so much discussion over this specific faction, I figured I might as well throw this up- a solution to the issue known as the Enclave, a solution that has been discussed a fair bit.

This PR will remain up until it's either manually declined or approved by a maintainer following a meeting wherein it will be brought up. In said meeting, I'll also bring up getting rid of the No-Mans land rules regarding no looting and whatnot, since they suck.

Enclave's been in a weird spot for too long. This is my answer.

image
image

## Why It's Good For The Game
- Less lag thanks to Casper being gone
- Less balance issues thanks to Enclave being gone outside of events
- Less lore issues now that the local enclave cell isn't going out 24/7

## Pre-Merge Checklist
- [ Y ] You tested this on a local server.
- [ Y ] This code did not runtime during testing.
- [ Y ] You documented all of your changes.

## Changelog
add: Enclave base to Dungeon Z-level
add: Seeds to Enclave base (incase it's enabled)
del: Casper Z-Level
tweak: Casper matrix normalized
balance: Enclave moved to Event Only (all slots set to 0)

### CODE REVIEW

**Comment by Weaselburg** [comment]
finally..... its over.......

**Comment by LynxSolstice** [comment]
You've stated multiple times that you hope the Enclave will be removed soon so you can take your character (Brenda Valerie) and use them as an Enclave Remnant Raider. This PR is entirely self-serving and only exists to punish people who have characters within the Enclave faction and for daring to try to put in the effort to revive the Enclave as a faction (which we've recently seen some success with).

**Comment by panzerr1944** [comment]
> You've stated multiple times that you hope the Enclave will be removed soon so you can take your character (Brenda Valerie) and use them as an Enclave Remnant Raider. This PR is entirely self-serving and only exists to punish people who have characters within the Enclave faction and for daring to try to put in the effort to revive the Enclave as a faction (which we've recently seen some success with).

I've stated numerous times that I'm fine with it being gone and that it's the most likely to get obliterated- with my solution to where I'm going to take my character if/when it's gone being to make them a raider. This PR isn't self-serving, as if you actually looked at it you'd realise this was made pre-emptively prior to a meeting it'll be brought up in as discussion revolving around their possible removal has been going on for quite some time- and to avoid FULL removal, I made this as to make them event-only.

If I wanted to punish people for playing Enclave then I'd certainly not have bothered keeping it in at all- nor would I have played it myself and put in effort to try and improve it (new base, etc). Something like this PR was bound to happen anyways- if not now then likely as the new map rolls around and I'd rather it be done by myself, as a player and coder of the faction, than someone else.

Kindly don't accuse me of being selfish simply because you want enclave to stick around in it's current mangled state.

**Comment by Stutternov** [comment]
How could someone be so brave..

**Comment by HissyNays** [comment]
I kinda hate the removal of casper, it couldn't have been causing that much lag.

**Comment by CaputCapital** [comment]
I'm on the fence about just outright removing the entire Enclave faction as a whole in lieu of relegating them to remnant outlaws and raiders. Moving the base to no man's land is fine but removing ALL of the slots?

This leaves the Enclave faction channel and Enclave involvement in previous events with uncertainty, where will the Enclave fit into the lore if these changes go through? If I were doing this PR differently, I would keep in the Scientist, Sergeant, Master Sergeant, and Lieutenant roles so that the faction isn't entirely obliterated off the table in terms of presence.

**Comment by panzerr1944** [comment]
> I'm on the fence about just outright removing the entire Enclave faction as a whole in lieu of relegating them to remnant outlaws and raiders. Moving the base to no man's land is fine but removing ALL of the slots?
> 
> This leaves the Enclave faction channel and Enclave involvement in previous events with uncertainty, where will the Enclave fit into the lore if these changes go through? If I were doing this PR differently, I would keep in the Scientist, Sergeant, Gunnery Sergeant, and Lieutenant roles so that the faction isn't entirely obliterated off the table in terms of presence.

They're being made event only. The slots are being set to 0 yet still available so all an admin needs to do to enable them for an event is flick up as many numbers as they need for an event. Keeping the jobs around and always accessible would invalidate the PR.

**Comment by CaputCapital** [comment]
> > I'm on the fence about just outright removing the entire Enclave faction as a whole in lieu of relegating them to remnant outlaws and raiders. Moving the base to no man's land is fine but removing ALL of the slots?
> > This leaves the Enclave faction channel and Enclave involvement in previous events with uncertainty, where will the Enclave fit into the lore if these changes go through? If I were doing this PR differently, I would keep in the Scientist, Sergeant, Gunnery Sergeant, and Lieutenant roles so that the faction isn't entirely obliterated off the table in terms of presence.
> 
> They're being made event only. The slots are being set to 0 yet still available so all an admin needs to do to enable them for an event is flick up as many numbers as they need for an event. Keeping the jobs around and always accessible would invalidate the PR.

But what events are being planned in advance for the Enclave faction. Is the narrative team and event staff in the process of planning events that include Enclave? I understand the point of keeping the slots at 0 and staff opening them for an Enclave event, but the outlook of events including Enclave just seem unlikely.

Brotherhood hasn't done much with Enclave around anyway, so there's another issue there.

**Comment by panzerr1944** [comment]
> > > I'm on the fence about just outright removing the entire Enclave faction as a whole in lieu of relegating them to remnant outlaws and raiders. Moving the base to no man's land is fine but removing ALL of the slots?
> > > This leaves the Enclave faction channel and Enclave involvement in previous events with uncertainty, where will the Enclave fit into the lore if these changes go through? If I were doing this PR differently, I would keep in the Scientist, Sergeant, Gunnery Sergeant, and Lieutenant roles so that the faction isn't entirely obliterated off the table in terms of presence.
> > 
> > 
> > They're being made event only. The slots are being set to 0 yet still available so all an admin needs to do to enable them for an event is flick up as many numbers as they need for an event. Keeping the jobs around and always accessible would invalidate the PR.
> 
> But what events are being planned in advance for the Enclave faction? Is the narrative team and event staff in the process of planning events that include Enclave? I understand the point of keeping the slots at 0 and staff opening them for an Enclave event, but the outlook of events including Enclave just seem unlikely with what's already in place with the Red Plague.
> 
> Brotherhood hasn't done much with Enclave around anyway, especially since they're most of the time bound to the bunker so there's another issue there.

No idea why I'm awake rn, but since I am;

I'm not on the lore-team. This PR handles the mechanical side of them going to event-only, should such be the course of action taken with the faction. I can't answer the lore questions yet nor any questions on what planned events might be since I simply do not have the answers myself for the aforementioned 'not on the lore team' reason. 

There's still meetings to be made and discussions to be had- with this PR being me getting it out of the way and done with on the mechanical side of things. If this PR ends up being unnecessary and Enclave doesn't get removed, then it will be closed.

**Comment by MaxStone2015** [comment]
Honestly this PR is a bad move, removing Enclave does nothing but drive a wedge already put in place deeper into the wound known as 'New Babylon', the public outcry was enough to warrant a new discussion regarding the potential avenues of how we could go about things. Casper can go, but the ENTIRE faction which has contributed to the narrative being nuked due to people 'not wanting to maintain it anymore', is frankly bullshit.

Relocate Enclave to sewers for all I care, but removing the entire faction and displacing dedicated players of an already shrinking playerbase is not the right call.

**Comment by Fishpoker** [comment]
> Honestly this PR is a bad move, removing Enclave does nothing but drive a wedge already put in place deeper into the wound known as 'New Babylon', the public outcry was enough to warrant a new discussion regarding the potential avenues of how we could go about things. Casper can go, but the ENTIRE faction which has contributed to the narrative being nuked due to people 'not wanting to maintain it anymore', is frankly bullshit.
> 
> Relocate Enclave to sewers for all I care, but removing the entire faction and displacing dedicated players of an already shrinking playerbase is not the right cal

> Honestly this PR is a bad move, removing Enclave does nothing but drive a wedge already put in place deeper into the wound known as 'New Babylon', the public outcry was enough to warrant a new discussion regarding the potential avenues of how we could go about things. Casper can go, but the ENTIRE faction which has contributed to the narrative being nuked due to people 'not wanting to maintain it anymore', is frankly bullshit.
> 
> Relocate Enclave to sewers for all I care, but removing the entire faction and displacing dedicated players of an already shrinking playerbase is not the right call.

Enclave really serves no pourpose besides getting their asses kicked hourly and dissapearing, and that almost every round they are active, if that even happens ( they are almost always dead). Only there because some mfs want to play in fancy PA i get the feeling. 
And if you want milsim play NCR

**Pull request closed without merging**
