### PR TITLE
Slightly changes bighorn bar's kitchen

### PR DESCRIPTION
**Pull request by K4rlox**
## About The Pull Request

moves a door, adds kitchen vendor, changes the fridge subtypes so they actually have required ingredients and meat in it
adds deepfrier
**adds a gibber, its behind the sign in map file so you cant see it**

## Why It's Good For The Game

several required changes to make the bighorn bar's kitchen way more efficent than normal, such as moving the door to have direct acess to the coldroom, changing the fridge types to add items, and a gibber

**once more the gibber is right there you cant see it because of the damn sign**
image

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: bighorn deepfrier
add: bighorn kitchen tools vendor
add: bighorn bar backroom gibber
tweak: changes the subtypes of fridges in bighorn
tweak: moves the door in bighorn bar to be less annoying
/:cl:

### CODE REVIEW

**Comment by maaacha** [comment]
remove the gibber and ill consider it, it can be used to RR and i'd rather not have it on the server

**Comment by K4rlox** [comment]
> remove the gibber and ill consider it, it can be used to RR and i'd rather not have it on the server

doing so rn

**Comment by K4rlox** [comment]
> remove the gibber and ill consider it, it can be used to RR and i'd rather not have it on the server

don

**Comment by K4rlox** [comment]
@maaacha does this make any conflicts and do i need to PR it again to fix conflicts

**Review by maaacha — APPROVED** [review]

**Pull request merged**
