### PR TITLE
Disables Slave Role

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Disables the slave role and adds an extra Aux slot as compensation.

Discussed this prior with lore-devs and not sure when this got re-enabled. This prevents admin headaches later on, allows staff to still open slots if really wanted for whatever reason, and honestly - Legion has plenty of follower slots and all. 

## Why It's Good For The Game

Read above - tl;dr: saves on drama, still allows admins to open slots if needed/wanted, not useful slots + creates the need for baby-sitting.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
removes: Slave slots.
adds: Aux slot as compensation. (You don't need more than that one, you have SEVEN camp follower slots already.)
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
Erm. Zased?

**Comment by BadAtThisGame302** [comment]
What a dumb PR, the Legion use slaves you know... sorry to BURST your bubble senior.

**Comment by AllCorruptingWyrm** [comment]
Yeah personally, when I've ever been enslaved, I just use it to sabotage the legion. it creates a lot of dumb ooc drama. When Noncon got banned the legion was 100x a lot better.

**Comment by Sapphirre** [comment]
I don't personally see how the slave role causes headaches for admins and promotes drama OOC. There are some players who actually do just play Legion to play Slave, and taking that away for a mostly unspecified reason doesn't add up much. Most slave players I've seen in-game provide more RP to Legion and aren't just there to be bait. 

Dunno if our feedback is accepted, but gonna have to **-1** on it.

**Review by maaacha — APPROVED** [review]
auxilia or camp follower can be used to play slave, this is to lower role bloat

**Pull request merged**
