### PR TITLE
Big Customisation Update

### PR DESCRIPTION
**Pull request by GreytidePanda**
## About The Pull Request
anyinterest

Adds in 269 new customisation parts. Many were ported and some were already in our codebase one way or another.

A few existing broken parts (no sprite and I can't find one anywhere) were removed. There was also an effort to alphabetise the part lists more, sort out the dmis (mam_markings.dmi is looking really neat now, check it out) and integrate modularised content (goodbye citadel snowflake.dm)

Also, species that were allowed hair but not facial hair were lifted from this restriction. (This is anthromorphs, synthetic anthromorphs, and synthetic lizardpeople.) This is especially useful for the new horn and tongue parts they have.

This was not a straight port - it took a while and I playtested it a bunch. But please please test merge first, there is a lot.

-59 New Hairstyles
> African Pigtails, Afro Puff Double, Afro Puff Left, Afro Puff Right, Astolfo, Baum, Belenko Tied, Belenko, Bluntbangs Alt, Bluntbangs, Cobra Hood, Combed Back, Combed Bob, Cotton Alt, Cotton Belle, Cotton Pigtails, Diagonal Bangs, Fortune Teller, Froofy, Geisha, Glam Metal, Hajime Alt, Hajime, Half-Shaved Glamorous, Half-Shaved Long Messy, Half-Shaved Long, Half-Shaved Messy, Harold, Long Straight Hair w/ Twin Tails, Long Fringe Alt, Pigtail Advanced, Quadcurls, Rockstar, Sharp Tail, Slightly Messy, Spicy, Tailhair, Vox Afro, Vox Crested Quills, Vox Cropped, Vox Emperor Quills, Vox Hawk, Vox Horns, Vox Keel Quills, Vox Keet Quills, Vox Kingly, Vox Mangy, Vox Mohawk, Vox Nights, Vox Ponytail, Vox Razor, Vox Razorclipped, Vox Rows, Vox Short Quills, Vox Surf, Vox Tiel Quills, Vox Yasu, Wife, Zone

-9 New Facial Hairs
> Face Horns, Chin Horns, Lizard Lick, Lizard Lick Fast, Lizard Lick Slow, Nose Lick, Nose Lick Fast, Nose Lick Slow, Tusks

-16 New Horns

> Antlers Wide, Billberry, Curly, Dragon, Dragon Inverted, Jackalope, Lizard, Ram Curled, Ram Curled Alt, Ram Small, Ram Small Alt, Ram Small Alt 2, Stabbers, Teppi, Unicorn, Upwards

-45 New Ears

> Antennae Face Alt, Antennae Face, Antennae Moth, Antennae Plume, Antennae Round, Antennae Thin, Avali, Big Wolf Both Piercings, Big Wolf Left Piercing, Big Wolf Right Piercing, Bunny Alt, Bunny Floppy, Bunny Long Alt, Bunny Long,  Bunny Tall Alt 2, Bunny Tall Alt, Bunny Tall, Cat Alt, Deer Alt, Eastern Dragon, Fan, Full Frill, Goat Horns, Goat, Gret, Jackal, Jackalope Tall, Long Frill, Lunasune, Miqo'te, Mouse Alt, Noodle Dragon, Pig, Pointy, Rosey, Sabresune, Sandfox Tall, Shadekin Tall, Shock, Spaniel, Split Frill, Teppi, Trike, Umbreon, Vaporeon

-47 New Snouts

> Beak Corvid, Beak Tiny, Cow, Deer, Deoxys, Duck, Eastern Dragon, Eastern Dragon Female, Eastern Dragon No Whiskers, Eastern Dragon No Whiskers, Female, Fox, Fox Alt, Goose, Magus, Mandible Big, Mandible Small, Orca, Otter, Owl, Proboscis, Rabbit, Rad-Dog, Rad-Dog Top, Rhino Beetle, Round Classic, Round Classic Top, Round + Light Classic, Round + Light Classic Top, Scarab, Sharp Alt, Sharp Classic, Sharp Classic Top, Sharp + Light Classic, Sharp + Light Classic Top, Short Alt, Skullbird Female, Skullbird Male, Sloog, Sloog Alt, Snub, Spider, Tajaran, Tajaran Short, Tarantula, Vulp, Vulp Alt, Zebra

-36 New Markings

> Abdominals 2-Tone, Abdominals 3-Tone, Abdominals, Backsail, Bands, Bee Alt, Bee Fluffy, Beetle, Belly Scutes, Belly Tajaran Full, Belly Tajaran, Body Gloss, Datashark, Dino Head, Eastern Dragon, Gradient, Moth, Patches, Paw Socks, Pigeon, Raccoon Alt, Rad-Dog, Sabresune, Shrike, Stego Chestplate, Stripes Back, Stripes Tiger, Tattoo Blush, Tattoo Campbell, Tattoo Lip, Tattoo Nightling, Tattoo Silverburgh, Tattoo Tiger, Trike Beak, Trike Horn, Umbreon

-12 New Wings

> Angel Moth, Harpy Arm Wings Alt Collar, Harpy Arm Wings Alt, Harpy Arm Wings Bat Collar, Harpy Arm Wings Bat, Harpy Arm Wings, Lugia, Pterodactyl, Robotic Alternate,  Spider Legs Fuzzy,  Spider Legs Plain, Spider Legs Spiky

-45 New Tails

> Bee Stinger, Gecko Big, Big Ring, Cat Slug, Club, Corgi, Demon Spade, Double Fox, Eastern Dragon, Feather, Furret, Gecko, Glaceon, Hawk Short, Insect 2 Tone, Kangaroo Large, Leafeon, Lizard Large, Long Fluff, Lunasune, Nightstalker Large, Ninetales, Octopus, Peacock Female, Peacock Male, Pig,  Pigeon Long, Pigeon Short, Pony Alt 1, Pony Alt 2, Pony Alt 3, Porkapine, Raptor, Sabresune,  Snake Large, Snep, Spike, Succubus, Swallow Striped, Swallow, Tail Maw, Turkey, Umbreon, Western Dragon Large, Xeno

## Why It's Good For The Game
More customisation options are always good.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added a lot more customisation options (hairs, ears, wings, etc)
/:cl:

### CODE REVIEW

**Comment by mazzinsanity** [comment]
Does the facial hair work on anthro species? I remember them not showing up

**Comment by Jinshee** [comment]
speedmerge PLS

**Comment by gummardgumphrey** [comment]
really good stuff, but are you able to also port over the gradient markings from skyrat to here as well? i know a lot of people have been requesting that.

**Comment by mopcat** [comment]
likely related to the above comment, the gradient markings are only partially colorable, with the majority of the marking being stark white. the below examples have the color for both leg and arm markings set to red for visibility.
image
image

**Comment by Draganfrukts** [comment]
Would love 2 have the fancy shark tails from skyrat that look more articulate and less like an ugly log
Shark and Fish, not Akula mind U

**Comment by mazzinsanity** [comment]
image
Server lead request.

**Comment by mazzinsanity** [comment]
Rename Scolipede parts as well, as it is a pokemon

**Review by maaacha — APPROVED** [review]

**Pull request merged**
