### PR TITLE
NCR base cooking updait

### PR DESCRIPTION
**Pull request by K4rlox**
## About The Pull Request

Tidies up the NCR kitchen, adds a fridge, adds a smoke machine, adds a food processor and a chef vendor

## Why It's Good For The Game

Local NCR chefs can now cook more stuff freely

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: changes NCR kitchen
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
Please post pictures of map areas edited.

Also - no smoke machines, please. They are very.. _very_ abusable

**Comment by K4rlox** [comment]
> Please post pictures of map areas edited.
> 
> Also - no smoke machines, please. They are very.. _very_ abusable

i fucking forgot

also, i didnt add smoke machines wdym?

**Comment by Stutternov** [comment]
read your own PRs description calling it a smoke machine..

Either way, seems fine then.

**Comment by K4rlox** [comment]
> read your own PRs description calling it a smoke machine..
> 
> Either way, seems fine then.

yeah i fucked up saying smoke machine but its technically a machine that sells smokes

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
