### PR TITLE
Brings back [REDACTED] button.

### PR DESCRIPTION
**Pull request by CloverIsLucky**
## About The Pull Request

Uncomments genital arousal button code, I hope nothing else was commented or deleted after the genital arousal button removal.

## Why It's Good For The Game

If we are a server that allows ERP, let us at least enjoy it with hardons. Why do we had this disabled in the first place?

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Brings back the Arousal button.
/:cl:

### CODE REVIEW

**Comment by mazzinsanity** [comment]
Yeah no

**Comment by maaacha** [comment]
No thanks.

**Comment by CloverIsLucky** [comment]
</3

**Comment by CloverIsLucky** [comment]
> Yeah no



> No thanks.

Why do we keep genitals then?

**Comment by Kepteyn** [comment]
It 

> No thanks.

This does seem like a bizarre decision. This is clearly a feature that is desired by some, and poses no downsides. If the problem is that it's fixing an issue with genitals, then remove the genitals alltogether.

**Pull request closed without merging**
